### PR TITLE
Integer rule

### PR DESCRIPTION
**Pull request by rajatjain4061**
I found IntegerRule was missing in the module so I created an IntegerRule class to validate integers.

### CODE REVIEW

**Comment by jpotts18** [comment]
Sorry for the delay @rajatjain4061 I don't do Swift in my day-to-day and this project is suffering. Would you be interested in becoming a contributor?

**Comment by rajatjain4061** [comment]
Yes, I am interested and would love to contribute more.

**Comment by jpotts18** [comment]
@rajatjain4061 I've just added you to the community can you please merge this PR

**Comment by jpotts18** [comment]
Also please make sure any necessary documentation and tests are added that prove the functionality changes. Still learning about permissions on organization so let me know if you see any hiccups making the changes

**Comment by rajatjain4061** [comment]
Thank you for adding me to the community. To merge this PR I need [write access](https://help.github.com/articles/what-are-the-different-access-permissions).

**Comment by rajatjain4061** [comment]
Please grant me write access to merge this PR.

**Comment by davepatterson** [comment]
@rajatjain4061 Are you saying that it's ready for merge as is? If so, I can merge it for you.

**Comment by rajatjain4061** [comment]
@davepatterson Yes please merge this.

**Comment by davepatterson** [comment]
@rajatjain4061 Merged!

**Pull request merged**
