### PR TITLE
Swift 4 migration

### PR DESCRIPTION
**Pull request by tarrgor**
I did a quick swift 4 migration, maybe it is helpful for you too :)

### CODE REVIEW

**Comment by Abdul-Hannan** [comment]
can someone please merge this PR and release a new version

**Comment by razanbilwani** [comment]
+1 for getting this merged asap

**Comment by tarrgor** [comment]
I think this has to be merged by the project owner. However in your Podfile you can also refer to my fork with
`pod 'SwiftValidator', :git => 'https://github.com/tarrgor/SwiftValidator.git', :branch => 'master'`
until it eventually gets merged back.

**Comment by matt-curtis** [comment]
@tarrgor Thanks for that!

**Pull request closed without merging**
