### PR TITLE
Migrate to Swift 5.0

### PR DESCRIPTION
**Pull request by AlbertArredondoAlfaro**
Migrate project to Swift 5.0

### CODE REVIEW

**Comment by paweljankowski** [comment]
@AlbertArredondoAlfaro Can you check why your PR fails?

**Comment by AlbertArredondoAlfaro** [comment]
@paweljankowski I have reverted my last commit. The issue is the update of the Xcode version on Travis. I thought it makes sense to apply this change, but honestly I don't know why then the CI fails to run.

**Comment by paweljankowski** [comment]
@RajatJain4061 Can you merge this ? We really need Swift 5 support :-)

**Comment by paweljankowski** [comment]
@jpotts18  Can you merge this PR ? Swift 5 support is really needed :-)

**Comment by andresilvagomez** [comment]
@AlbertArredondoAlfaro I'm using right now your master branch with Carthage but it's return 

```Build Failed
Task failed with exit code 65:
/usr/bin/xcrun xcodebuild -project .../Carthage/Checkouts/SwiftValidator/Validator.xcodeproj -scheme SwiftValidator -configuration Release -derivedDataPath .../Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/SwiftValidator/5.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/xv/7py__ckn12sbt71zvdbpw44m0000gn/T/SwiftValidator SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /...l/Carthage/Checkouts/SwiftValidator)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/xv/7py__ckn12sbt71zvdbpw44m0000gn/T/carthage-xcodebuild.MaJfz1.log```

**Comment by AlbertArredondoAlfaro** [comment]
@andresilvagomez You should use the "Swift-5.0" branch.

**Comment by shift00** [comment]
@AlbertArredondoAlfaro where is "Swift-5.0" branch? Carthage can't update SwiftValidator with 5.0 syntax from master branch :(

**Comment by shift00** [comment]
> @AlbertArredondoAlfaro where is "Swift-5.0" branch? Carthage can't update SwiftValidator with 5.0 syntax from master branch :(

I found this - https://github.com/AlbertArredondoAlfaro/SwiftValidator/tree/swift-5.0 ;)

**Comment by AlbertArredondoAlfaro** [comment]
Hi @shift00, you are right, you should use the  https://github.com/AlbertArredondoAlfaro/SwiftValidator/tree/swift-5.0 branch.

**Pull request merged**
